name: GitHub CI Action
on: ["push", "pull_request"]
jobs:
  #####----- MYTEMPLATE FULL TESTING OF INSTALLED PACKAGE WITHOUT COVERAGE
  test_mytemplate:
    runs-on: ${{ matrix.os }}
    strategy:
      # python-versions must be maintained consistent with associated setup.py
      # and tox.ini configuration.
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
    ##-- General Setup Steps
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup python with tox
      run: ./.github/workflows/setup_tox_github_action.sh

    ##-- Test Execution Step
    - name: Test mytemplate python package
      run: |
        pushd mytemplate_pypkg
        tox -r -e py-nocoverage
        popd

  #####----- MYTEMPLATE2 FULL TESTING OF INSTALLED PACKAGE WITHOUT COVERAGE
  test_mytemplate2:
    runs-on: ${{ matrix.os }}
    strategy:
      # python-versions must be maintained consistent with associated setup.py
      # and tox.ini configuration.
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    ##-- General Setup Steps
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup python with tox
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install wheel
        pip install tox
        echo
        which python
        which pip
        which tox
        echo
        python --version
        pip --version
        tox --version
        echo
        pip list

    ##-- Test Execution Step
    - name: Test mytemplate2 python package
      run: |
        pushd mytemplate2_pypkg
        tox -r -e py-nocoverage
        popd

  #####----- MEASURE COVERAGE ACROSS ALL PACKAGES
  coverage_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      # We only need to measure coverage with a single python version, and we
      # must pick a version that all packages include via tox.  Ideally this
      # will be the latest version of python used in the action.
      matrix:
        python-version: ["3.11"]
    steps:
    ##-- General Setup Steps
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup python with tox
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install wheel
        pip install tox
        echo
        which python
        which pip
        which tox
        echo
        python --version
        pip --version
        tox --version
        echo
        pip list

    ##-- Run Coverage for All Packages
    # Coverage is full test suite run on local clone so that coveralls
    # has nice output.  Generate html report to export as artifact.
    - name: Generate all coverage for coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # We want to preserve all individual coverage results as artifacts.
        # Therefore, save each of these to a unique file .coverage_<package name>
        # Save all in root of repo for later aggregation.
        pushd mytemplate_pypkg
        COVERAGE_FILE=../.coverage_mytemplate tox -r -e py-coverage
        popd
        pushd mytemplate2_pypkg
        COVERAGE_FILE=../.coverage_mytemplate2 tox -r -e py-coverage
        popd
        # This aggregates into .coverage for coveralls
        tox -r -e aggregate,coveralls,report -- ./.coverage_*

    ##-- Publish full coverage report as artifact
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-results
        path: |
            .coverage*
            htmlcov

    ##-- Publish mytemplate distributions
    # These are pure python and don't depend on OS or python version used
    # for testing
    - name: Archive tested mytemplate distributions
      uses: actions/upload-artifact@v3
      with:
        name: tested-mytemplate-packages
        path: |
          mytemplate_pypkg/.tox/.pkg/dist/mytemplate-*.whl
          mytemplate_pypkg/.tox/.pkg/dist/mytemplate-*.tar.gz

    ##-- Publish mytemplate2 distributions
    # These are pure python and don't depend on OS or python version used
    # for testing
    - name: Archive tested mytemplate2 distributions
      uses: actions/upload-artifact@v3
      with:
        name: tested-mytemplate2-packages
        path: |
          mytemplate2_pypkg/.tox/.pkg/dist/mytemplate2-*.whl
          mytemplate2_pypkg/.tox/.pkg/dist/mytemplate2-*.tar.gz

